from abc import ABC, abstractmethod
from enum import StrEnum

"""Abstract interfaces for Ticketing APIs generated by pyright."""
class TicketStatus(StrEnum):
    OPEN = ...
    IN_PROGRESS = ...
    CLOSED = ...


class Ticket(ABC):
    @property
    @abstractmethod
    def id(self) -> str:
        ...

    @property
    @abstractmethod
    def title(self) -> str:
        ...

    @property
    @abstractmethod
    def description(self) -> str:
        ...

    @property
    @abstractmethod
    def status(self) -> TicketStatus:
        ...

    @property
    @abstractmethod
    def assignee(self) -> str | None:
        ...

class TicketInterface(ABC):
    @abstractmethod
    def create_ticket(self, title: str, description: str, assignee: str | None = ...) -> Ticket:
        ...

    @abstractmethod
    def get_ticket(self, ticket_id: str) -> Ticket | None:
        ...

    @abstractmethod
    def search_tickets(self, query: str | None = ..., status: TicketStatus | None = ...) -> list[Ticket]:
        ...

    @abstractmethod
    def update_ticket(self, ticket_id: str, status: TicketStatus | None = ..., title: str | None = ...) -> Ticket:
        ...

    @abstractmethod
    def delete_ticket(self, ticket_id: str) -> bool:
        ...
